apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./deployment.yaml
- ./service.yaml
commonLabels:
  app: demo-nginx
images:
- name: 767397827522.dkr.ecr.ap-northeast-2.amazonaws.com/eks-demo-repo
  newTag: "90"
